name: jobs examples

on:
   push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create an artefact for reuse
        run: echo "Full feature artifact" > build-result.txt


  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: use of artefact created
        run: ls build-result.txt
