on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: On Monday or Wednesday
        if: github.event.schedule == '30 5 * * 1,3'
        run: echo "This step will run on Monday and Wednesday"
      - name: On Tuesday or Thursday
        if: github.event.schedule == '30 5 * * 2,4'
        run: echo "This step will run on Tuesday or Thursday"
      - name: Every time
        run: echo "This step will always run"
